name: Build and Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 zip

      - name: Build Project
        run: make all

      - name: Archive Build Artifacts
        run: |
          # Package Linux binary into a tar.gz
          tar -czvf BF-Linux.tar.gz -C build BF.x86_64.elf
          
          # Package Windows binaries into separate zip files
          cd build
          zip ../BF-Win64.zip BF.win64.exe
          zip ../BF-Win32.zip BF.win32.exe
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            BF-Linux.tar.gz
            BF-Win64.zip
            BF-Win32.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
