name: Build and Release
on:
  push:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build project
        run: make all

      - name: Archive Build
        run: tar -czvf BF.tar.gz ./build


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: BF.tar.gz
          generate_release_notes: true
          tag: AUTO-BUILD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
